/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2023-09-03 03:11:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.xuliyi.learnjava.bean.TypeBean;
import com.xuliyi.learnjava.dao.AdminDao;
import com.xuliyi.learnjava.dao.TypeDao;
import com.xuliyi.learnjava.bean.BookBean;
import com.xuliyi.learnjava.dao.BookDao;
import com.xuliyi.learnjava.bean.AdminBean;

public final class admin_005fbook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xuliyi.learnjava.dao.AdminDao");
    _jspx_imports_classes.add("com.xuliyi.learnjava.dao.TypeDao");
    _jspx_imports_classes.add("com.xuliyi.learnjava.bean.BookBean");
    _jspx_imports_classes.add("com.xuliyi.learnjava.bean.TypeBean");
    _jspx_imports_classes.add("com.xuliyi.learnjava.dao.BookDao");
    _jspx_imports_classes.add("com.xuliyi.learnjava.bean.AdminBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html lang=\"zh-CN\" class=\"ax-vertical-centered\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>图书馆管理系统</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap-theme.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap-admin-theme.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap-admin-theme.css\">\n");
      out.write("<script src=\"static/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"static/jQuery/jquery-3.1.1.min.js\"></script>\n");
      out.write("<script src=\"static/js/bootstrap-dropdown.min.js\"></script>\n");
      out.write("<script src=\"static/js/adminUpdateInfo.js\"></script>\n");
      out.write("<script src=\"static/js/adminUpdatePwd.js\"></script>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	background-image: url(\"01.jpg\");\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<script src=\"static/js/jquery.min.js\"></script>\n");
      out.write("<script src=\"static/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<body class=\"bootstrap-admin-with-small-navbar\">\n");
      out.write("	");

		AdminBean admin = new AdminBean();
		String aid = (String) session.getAttribute("aid");
		AdminDao admindao = new AdminDao();
		admin = admindao.get_AidInfo2(aid);
	
      out.write("\n");
      out.write("	<nav\n");
      out.write("		class=\"navbar navbar-inverse navbar-fixed-top bootstrap-admin-navbar bootstrap-admin-navbar-under-small\"\n");
      out.write("		role=\"navigation\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-lg-12\">\n");
      out.write("					<div class=\"collapse navbar-collapse main-navbar-collapse\">\n");
      out.write("						<a class=\"navbar-brand\" href=\"admin.jsp\"><strong>欢迎使用图书馆管理系统</strong></a>\n");
      out.write("						<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("							<li class=\"dropdown\"><a href=\"#\" role=\"button\"\n");
      out.write("								class=\"dropdown-toggle\" data-hover=\"dropdown\"> <i\n");
      out.write("									class=\"glyphicon glyphicon-user\"></i> 欢迎您，");
out.write(admin.getName());
      out.write("\n");
      out.write("										(");
      out.print(session.getAttribute("aid"));
      out.write(") <i class=\"caret\"></i></a>\n");
      out.write("								<ul class=\"dropdown-menu\">\n");
      out.write("									<li><a href=\"#updateinfo\" data-toggle=\"modal\">个人资料</a></li>\n");
      out.write("									<li role=\"presentation\" class=\"divider\"></li>\n");
      out.write("									<li><a href=\"#updatepwd\" data-toggle=\"modal\">修改密码</a></li>\n");
      out.write("									<li role=\"presentation\" class=\"divider\"></li>\n");
      out.write("									<li><a href=\"login.jsp\">退出</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<!-- left, vertical navbar & content -->\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<!-- left, vertical navbar -->\n");
      out.write("			<div class=\"col-md-2 bootstrap-admin-col-left\">\n");
      out.write("				<ul class=\"nav navbar-collapse collapse bootstrap-admin-navbar-side\">\n");
      out.write("					<li><a href=\"admin_book.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 图书管理</a></li>\n");
      out.write("					<li><a href=\"admin_user.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 读者管理</a></li>\n");
      out.write("					<li><a href=\"admin_booktype.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 图书分类管理</a></li>\n");
      out.write("					<li><a href=\"admin_borrow.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 图书借阅信息</a></li>\n");
      out.write("					<li><a href=\"admin_history.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 图书归还信息</a></li>\n");
      out.write("					<li><a href=\"admin_login.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i>管理员管理(需登录)</a></li>\n");
      out.write("				</ul><br><br>\n");
      out.write("				<ul class=\"nav navbar-collapse collapse bootstrap-admin-navbar-side\">\n");
      out.write("					<li><a href=\"admin_bdtimes.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 热门推荐</a></li>\n");
      out.write("					<li><a href=\"admin_brtimes.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 最佳读者</a></li>\n");
      out.write("				</ul><br><br>\n");
      out.write("				<ul class=\"nav navbar-collapse collapse bootstrap-admin-navbar-side\">\n");
      out.write("					<li><a href=\"admin_feedback.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 读者反馈</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<!-- content -->\n");
      out.write("			<div class=\"col-md-10\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-lg-12\">\n");
      out.write("						<div class=\"panel panel-default bootstrap-admin-no-table-panel\">\n");
      out.write("							<div class=\"panel-heading\">\n");
      out.write("								<div class=\"text-muted bootstrap-admin-box-title\">查询</div>\n");
      out.write("							</div>\n");
      out.write("							<div\n");
      out.write("								class=\"bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in\">\n");
      out.write("								<form class=\"form-horizontal\" action=\"selectServlet\"\n");
      out.write("									method=\"post\">\n");
      out.write("									<!-- <input type=\"hidden\" name=\"tip\" value=\"1\"> -->\n");
      out.write("									<input type=\"hidden\" name=\"tip\" value=\"1\">\n");
      out.write("									<div class=\"col-lg-7 form-group\">\n");
      out.write("										<label class=\"col-lg-4 control-label\" for=\"query_bname\">图书信息</label>\n");
      out.write("										<div class=\"col-lg-8\">\n");
      out.write("											<input class=\"form-control\" id=\"bookName\" name=\"name\"\n");
      out.write("												type=\"text\" value=\"\"> <label class=\"control-label\"\n");
      out.write("												for=\"query_bname\" style=\"display: none;\"></label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col-lg-3 form-group\">\n");
      out.write("\n");
      out.write("										<button type=\"submit\" class=\"btn btn-primary\" id=\"btn_query\">查询</button>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col-lg-3 form-group\">\n");
      out.write("										<button type=\"button\" class=\"btn btn-primary\" id=\"btn_add\"\n");
      out.write("											data-toggle=\"modal\" data-target=\"#addModal\">添加图书</button>\n");
      out.write("									</div>\n");
      out.write("								</form>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-lg-12\">\n");
      out.write("						<table id=\"data_list\" class=\"table table-hover table-bordered\"\n");
      out.write("							cellspacing=\"0\" width=\"100%\">\n");
      out.write("							<thead>\n");
      out.write("								<tr>\n");
      out.write("									<th>图书号</th>\n");
      out.write("									<th>图书类型</th>\n");
      out.write("									<th>图书名称</th>\n");
      out.write("									<th>作者名称</th>\n");
      out.write("									<th>出版社</th>\n");
      out.write("									<th>总数量</th>\n");
      out.write("									<th>操作</th>\n");
      out.write("								</tr>\n");
      out.write("							</thead>\n");
      out.write("\n");
      out.write("							<!---在此插入信息-->\n");
      out.write("							");

								ArrayList<BookBean> bookdata = new ArrayList<BookBean>();
								bookdata = (ArrayList<BookBean>) request.getAttribute("data");
								if (bookdata == null) {
									BookDao bookdao = new BookDao();
									bookdata = (ArrayList<BookBean>) bookdao.get_ListInfo();
								}
	
								for (BookBean bean : bookdata) {
							
      out.write("\n");
      out.write("							<tbody>\n");
      out.write("								<td>");
      out.print(bean.getCard());
      out.write("</td>\n");
      out.write("								<td>");
      out.print(bean.getType());
      out.write("</td>\n");
      out.write("								<td>");
      out.print(bean.getName());
      out.write("</td>\n");
      out.write("								<td>");
      out.print(bean.getAutho());
      out.write("</td>\n");
      out.write("								<td>");
      out.print(bean.getPress());
      out.write("</td>\n");
      out.write("								<td>");
      out.print(bean.getNum());
      out.write("</td>\n");
      out.write("								<td><button type=\"button\" class=\"btn btn-warning btn-xs\"\n");
      out.write("										data-toggle=\"modal\" data-target=\"#updateModal\" id=\"btn_update\"\n");
      out.write("										onclick=\"showInfo2('");
      out.print(bean.getBid());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(bean.getCard());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(bean.getType());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(bean.getName());
      out.write("',\n");
      out.write("											'");
      out.print(bean.getAutho());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(bean.getPress());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(bean.getNum());
      out.write("')\">修改</button>\n");
      out.write("									<button type=\"button\" class=\"btn btn-danger btn-xs\"\n");
      out.write("										onclick=\"deletebook(");
      out.print(bean.getBid());
      out.write(")\">删除</button></td>\n");
      out.write("							</tbody>\n");
      out.write("							");

								}
							
      out.write("\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		function showInfo2(bid, card, type, name, autho, press, num) {\n");
      out.write("			document.getElementById(\"updateISBN\").value = card;\n");
      out.write("			document.getElementById(\"updateBookName\").value = name;\n");
      out.write("			document.getElementById(\"updateAutho\").value = autho;\n");
      out.write("			document.getElementById(\"updatePress\").value = press;\n");
      out.write("			document.getElementById(\"updateBookType\").value = type;\n");
      out.write("			document.getElementById(\"updateNum\").value = num;\n");
      out.write("			document.getElementById(\"updateBookId\").value = bid;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		function deletebook(bid) {\n");
      out.write("			con = confirm(\"是否删除?\");\n");
      out.write("			if(con == true) {\n");
      out.write("				location.href = \"deleteServlet?bid=\" + bid;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("	<!-------------------------------------------------------------->\n");
      out.write("\n");
      out.write("	<!-- 修改模态框（Modal） -->\n");
      out.write("	<form class=\"form-horizontal\" method=\"post\"\n");
      out.write("		action=\"updateBookServlet\">\n");
      out.write("		<!--保证样式水平不混乱-->\n");
      out.write("		<div class=\"modal fade\" id=\"updateModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-labelledby=\"updateModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("							aria-hidden=\"true\">&times;</button>\n");
      out.write("						<h4 class=\"modal-title\" id=\"updateModalLabel\">修改图书信息</h4>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("\n");
      out.write("						<!---------------------表单-------------------->\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">图书号</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"hidden\" id=\"updateBookId\" name=\"updatebid\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"updateISBN\"\n");
      out.write("									name=\"card\" placeholder=\"请输入书号\"> <label\n");
      out.write("									class=\"control-label\" for=\"updateISBN\" style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">图书名称</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"updateBookName\"\n");
      out.write("									name=\"name\" placeholder=\"请输入图书名称\"> <label\n");
      out.write("									class=\"control-label\" for=\"updateBookName\"\n");
      out.write("									style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">图书类型</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<select class=\"form-control\" id=\"updateBookType\" name=\"type\"\n");
      out.write("									onPropertyChange=\"showValue(this.value)\">\n");
      out.write("									<option value=\"-1\">请选择</option>\n");
      out.write("									");

										TypeDao typedao = new TypeDao();
										ArrayList<TypeBean> data = (ArrayList<TypeBean>) typedao.get_ListInfo();
										data = (ArrayList<TypeBean>) typedao.get_ListInfo();
										for (TypeBean bean : data) {
									
      out.write("\n");
      out.write("									<option value=\"");
      out.print(bean.getName());
      out.write("\">\n");
      out.write("										");
      out.print(bean.getName());
      out.write("\n");
      out.write("									</option>\n");
      out.write("									");

										}
									
      out.write("\n");
      out.write("								</select> <label class=\"control-label\" for=\"updateBookType\"\n");
      out.write("									style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">作者名称</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"updateAutho\"\n");
      out.write("									name=\"autho\" placeholder=\"请输入作者名称\"> <label\n");
      out.write("									class=\"control-label\" for=\"updateAutho\" style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">出版社</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"updatePress\"\n");
      out.write("									name=\"press\" placeholder=\"请输入出版社\"> <label\n");
      out.write("									class=\"control-label\" for=\"updatePress\" style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">总数量</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"updateNum\"\n");
      out.write("									name=\"num\" placeholder=\"请输入总数量\"> <label\n");
      out.write("									class=\"control-label\" for=\"updatePress\" style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">修改</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- /.modal-content -->\n");
      out.write("			</div>\n");
      out.write("			<!-- /.modal -->\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("	<!-------------------------------------------------------------->\n");
      out.write("\n");
      out.write("	<!--------------------------------------添加的模糊框------------------------>\n");
      out.write("	<form class=\"form-horizontal\" method=\"post\"\n");
      out.write("		action=\"AddBookServlet\">\n");
      out.write("		<!--保证样式水平不混乱-->\n");
      out.write("		<!-- 模态框（Modal） -->\n");
      out.write("		<div class=\"modal fade\" id=\"addModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("							aria-hidden=\"true\">&times;</button>\n");
      out.write("						<h4 class=\"modal-title\" id=\"myModalLabel\">添加新图书</h4>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("\n");
      out.write("						<!---------------------表单-------------------->\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">图书号</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"addISBN\"\n");
      out.write("									required=\"required\" name=\"card\" placeholder=\"请输入书号\"> <label\n");
      out.write("									class=\"control-label\" for=\"addISBN\" style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">图书名称</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"addBookName\"\n");
      out.write("									required=\"required\" name=\"name\" placeholder=\"请输入图书名称\">\n");
      out.write("								<label class=\"control-label\" for=\"addBookName\"\n");
      out.write("									style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">图书类型</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<select class=\"form-control\" id=\"addBookType\" name=\"type\">\n");
      out.write("									<option value=\"无分类\">请选择</option>\n");
      out.write("									");

										data = (ArrayList<TypeBean>) typedao.get_ListInfo();
										for (TypeBean bean : data) {
									
      out.write("\n");
      out.write("									<option value=\"");
      out.print(bean.getName());
      out.write("\">\n");
      out.write("										");
      out.print(bean.getName());
      out.write("\n");
      out.write("									</option>\n");
      out.write("									");

										}
									
      out.write("\n");
      out.write("								</select> <label class=\"control-label\" for=\"addBookType\"\n");
      out.write("									style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">作者名称</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"addAutho\"\n");
      out.write("									required=\"required\" name=\"autho\" placeholder=\"请输入作者名称\">\n");
      out.write("								<label class=\"control-label\" for=\"addAutho\"\n");
      out.write("									style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">出版社</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"addPress\"\n");
      out.write("									required=\"required\" name=\"press\" placeholder=\"请输入出版社\">\n");
      out.write("								<label class=\"control-label\" for=\"addPress\"\n");
      out.write("									style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">总数量</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"addNum\"\n");
      out.write("									required=\"required\" name=\"num\" placeholder=\"请输入图书总数量\">\n");
      out.write("								<label class=\"control-label\" for=\"addNum\" style=\"display: none;\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<!---------------------表单-------------------->\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">添加</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- /.modal-content -->\n");
      out.write("			</div>\n");
      out.write("			<!-- /.modal -->\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("	<!--------------------------------------修改密码的模糊框------------------------>\n");
      out.write("\n");
      out.write("	<!-------------------------------------------------------------->\n");
      out.write("\n");
      out.write("	<form class=\"form-horizontal\" method=\"post\"\n");
      out.write("		action=\"AdminServlet\">\n");
      out.write("		<!--保证样式水平不混乱-->\n");
      out.write("		<!-- 模态框（Modal） -->\n");
      out.write("		<div class=\"modal fade\" id=\"updatepwd\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("							aria-hidden=\"true\">&times;</button>\n");
      out.write("						<h4 class=\"modal-title\" id=\"myModalLabel\">修改密码</h4>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("\n");
      out.write("						<!--正文-->\n");
      out.write("						<input type=\"hidden\" name=\"tip\" value=\"1\"> <input\n");
      out.write("							type=\"hidden\" name=\"url\" value=\"admin_book\">\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">原密码</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"password\" class=\"form-control\" name=\"password\"\n");
      out.write("									id=\"oldPwd\" placeholder=\"请输入原密码\"> <label\n");
      out.write("									class=\"control-label\" for=\"oldPwd\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">新密码</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"password\" class=\"form-control\" name=\"password2\"\n");
      out.write("									id=\"newPwd\" placeholder=\"请输入新密码\"> <label\n");
      out.write("									class=\"control-label\" for=\"newPwd\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">修改</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- /.modal-content -->\n");
      out.write("			</div>\n");
      out.write("			<!-- /.modal -->\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("	<!-------------------------------------------------------------->\n");
      out.write("\n");
      out.write("	<!-------------------------个人资料模糊框------------------------------------->\n");
      out.write("\n");
      out.write("	<form class=\"form-horizontal\" method=\"post\"\n");
      out.write("		action=\"AdminServlet\">\n");
      out.write("		<!--保证样式水平不混乱-->\n");
      out.write("		<!-- 模态框（Modal） -->\n");
      out.write("		<div class=\"modal fade\" id=\"updateinfo\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-labelledby=\"ModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("							aria-hidden=\"true\">&times;</button>\n");
      out.write("						<h4 class=\"modal-title\" id=\"ModalLabel\">个人资料</h4>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("\n");
      out.write("						<!--正文-->\n");
      out.write("						<input type=\"hidden\" name=\"tip\" value=\"2\"> <input\n");
      out.write("							type=\"hidden\" name=\"url\" value=\"admin_book\">\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">真实姓名</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\"\n");
      out.write("									placeholder=\"请输入您的真实姓名\" value='");
out.write(admin.getName());
      out.write("'>\n");
      out.write("								<label class=\"control-label\" for=\"name\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">手机号</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\"\n");
      out.write("									placeholder=\"请输入您的手机号\" value='");
out.write(admin.getPhone());
      out.write("'>\n");
      out.write("								<label class=\"control-label\" for=\"phone\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">邮箱</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\"\n");
      out.write("									placeholder=\"请输入您的邮箱\" value='");
out.write(admin.getEmail());
      out.write("'>\n");
      out.write("								<label class=\"control-label\" for=\"email\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">修改</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- /.modal-content -->\n");
      out.write("			</div>\n");
      out.write("			<!-- /.modal -->\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
