/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2023-09-03 03:14:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.xuliyi.learnjava.bean.AdminBean;
import com.xuliyi.learnjava.dao.AdminDao;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xuliyi.learnjava.dao.AdminDao");
    _jspx_imports_classes.add("com.xuliyi.learnjava.bean.AdminBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	if (session.getAttribute("aid") == null){
		response.sendRedirect(request.getContextPath() + "/login.jsp");
	}	

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html lang=\"zh-CN\" class=\"ax-vertical-centered\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>图书馆管理系统</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap-theme.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap-admin-theme.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap-admin-theme.css\">\n");
      out.write("<script src=\"static/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"static/jQuery/jquery-3.1.1.min.js\"></script>\n");
      out.write("<script src=\"static/js/bootstrap-dropdown.min.js\"></script>\n");
      out.write("<script src=\"static/js/reader.js\"></script>\n");
      out.write("<script src=\"static/js/readerUpdateInfo.js\"></script>\n");
      out.write("<script src=\"static/js/readerUpdatePwd.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	background-image: url(\"03.jpg\");\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"static/js/jquery.min.js\"></script>\n");
      out.write("<script src=\"static/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"bootstrap-admin-with-small-navbar\">\n");
      out.write("	<!-- 判断是否已经登录 -->\n");
      out.write("	");

		AdminBean admin = new AdminBean();
		String aid = (String) session.getAttribute("aid");
		AdminDao admindao = new AdminDao();
		admin = admindao.get_AidInfo2(aid);
	
      out.write("\n");
      out.write("	<nav\n");
      out.write("		class=\"navbar navbar-inverse navbar-fixed-top bootstrap-admin-navbar bootstrap-admin-navbar-under-small\"\n");
      out.write("		role=\"navigation\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-lg-12\">\n");
      out.write("					<div class=\"collapse navbar-collapse main-navbar-collapse\">\n");
      out.write("						<a class=\"navbar-brand\" href=\"index.jsp\"><strong>欢迎使用图书馆管理系统</strong></a>\n");
      out.write("						<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("							<li class=\"dropdown\"><a href=\"#\" role=\"button\"\n");
      out.write("								class=\"dropdown-toggle\" data-hover=\"dropdown\"> <i\n");
      out.write("									class=\"glyphicon glyphicon-user\"></i> 欢迎您，${admin.getName()}\n");
      out.write("										(");
      out.print(session.getAttribute("aid"));
      out.write(")\n");
      out.write("									<i class=\"caret\"></i></a>\n");
      out.write("								<ul class=\"dropdown-menu\">\n");
      out.write("									<li><a href=\"#updateinfo\" data-toggle=\"modal\">个人资料</a></li>\n");
      out.write("									<li role=\"presentation\" class=\"divider\"></li>\n");
      out.write("									<li><a href=\"#updatepwd\" data-toggle=\"modal\">修改密码</a></li>\n");
      out.write("									<li role=\"presentation\" class=\"divider\"></li>\n");
      out.write("									<li><a href=\"login.jsp\">退出</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<!-- left, vertical navbar & content -->\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<!-- left, vertical navbar -->\n");
      out.write("			<div class=\"col-md-2 bootstrap-admin-col-left\">\n");
      out.write("				<ul class=\"nav navbar-collapse collapse bootstrap-admin-navbar-side\">\n");
      out.write("					<li><a href=\"select.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 图书查询</a></li>\n");
      out.write("					<li><a href=\"borrow.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 借阅信息</a></li>\n");
      out.write("					<li><a href=\"history.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 借阅历史</a></li>\n");
      out.write("				</ul><br><br>\n");
      out.write("				<ul class=\"nav navbar-collapse collapse bootstrap-admin-navbar-side\">\n");
      out.write("					<li><a href=\"bdtimes.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 热门推荐</a></li>\n");
      out.write("					<li><a href=\"brtimes.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 最佳读者</a></li>\n");
      out.write("				</ul><br><br>\n");
      out.write("				<ul class=\"nav navbar-collapse collapse bootstrap-admin-navbar-side\">\n");
      out.write("					<li><a href=\"feedback.jsp\"><i\n");
      out.write("							class=\"glyphicon glyphicon-chevron-right\"></i> 问题反馈</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<!-- content -->\n");
      out.write("			<div class=\"col-md-10\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"panel panel-default\">\n");
      out.write("							<div class=\"panel-heading\">\n");
      out.write("								<div class=\"text-muted bootstrap-admin-box-title\">图书查询</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"bootstrap-admin-panel-content\">\n");
      out.write("								<ul>\n");
      out.write("									<li>根据图书名称、作者、分类查询图书信息</li>\n");
      out.write("									<li>可查询图书的编号、名称、分类、作者、在馆数量等</li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- 判断用户是否登录 -->\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"panel panel-default\">\n");
      out.write("							<div class=\"panel-heading\">\n");
      out.write("								<div class=\"text-muted bootstrap-admin-box-title\">借阅信息</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"bootstrap-admin-panel-content\">\n");
      out.write("								<ul>\n");
      out.write("									<li>展示所借图书的基本信息，借阅日期、截止还书日期等</li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"panel panel-default\">\n");
      out.write("							<div class=\"panel-heading\">\n");
      out.write("								<div class=\"text-muted bootstrap-admin-box-title\">热门推荐</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"bootstrap-admin-panel-content\">\n");
      out.write("								<ul>\n");
      out.write("									<li>展示每一本书的借阅量，包括图书基本信息</li>\n");
      out.write("									<li>可以在当前界面直接借阅，并且可以查询书籍借阅量</li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"panel panel-default\">\n");
      out.write("							<div class=\"panel-heading\">\n");
      out.write("								<div class=\"text-muted bootstrap-admin-box-title\">借阅历史</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"bootstrap-admin-panel-content\">\n");
      out.write("								<ul>\n");
      out.write("									<li>查询借阅历史，借阅时长等具体信息</li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"panel panel-default\">\n");
      out.write("							<div class=\"panel-heading\">\n");
      out.write("								<div class=\"text-muted bootstrap-admin-box-title\">最佳读者</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"bootstrap-admin-panel-content\">\n");
      out.write("								<ul>\n");
      out.write("									<li>展示每一位已知读者的借阅量，以及读者的基本信息</li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"panel panel-default\">\n");
      out.write("							<div class=\"panel-heading\">\n");
      out.write("								<div class=\"text-muted bootstrap-admin-box-title\">问题反馈</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"bootstrap-admin-panel-content\">\n");
      out.write("								<ul>\n");
      out.write("									<li>有问题请留下您的联系方式，我们会记录在库并及时反馈</li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-------------------------------------------------------------->\n");
      out.write("\n");
      out.write("	<form class=\"form-horizontal\" method=\"post\"\n");
      out.write("		action=\"AdminServlet\">\n");
      out.write("		<!--保证样式水平不混乱-->\n");
      out.write("		<!-- 模态框（Modal） -->\n");
      out.write("		<div class=\"modal fade\" id=\"updatepwd\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("							aria-hidden=\"true\">&times;</button>\n");
      out.write("						<h4 class=\"modal-title\" id=\"myModalLabel\">修改密码</h4>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("\n");
      out.write("						<!--正文-->\n");
      out.write("						<input type=\"hidden\" name=\"tip\" value=\"1\"> <input\n");
      out.write("							type=\"hidden\" name=\"url\" value=\"index\">\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">原密码</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"password\" class=\"form-control\" name=\"password\"\n");
      out.write("									id=\"oldPwd\" placeholder=\"请输入原密码\"> <label\n");
      out.write("									class=\"control-label\" for=\"oldPwd\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">新密码</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"password\" class=\"form-control\" name=\"password2\"\n");
      out.write("									id=\"newPwd\" placeholder=\"请输入新密码\"> <label\n");
      out.write("									class=\"control-label\" for=\"newPwd\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<!--正文-->\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\n");
      out.write("						</button>\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">修改</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- /.modal-content -->\n");
      out.write("			</div>\n");
      out.write("			<!-- /.modal -->\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("	<!-------------------------------------------------------------->\n");
      out.write("\n");
      out.write("	<!-------------------------个人资料模糊框------------------------------------->\n");
      out.write("\n");
      out.write("	<form class=\"form-horizontal\" method=\"post\"\n");
      out.write("		action=\"AdminServlet\">\n");
      out.write("		<!--保证样式水平不混乱-->\n");
      out.write("		<!-- 模态框（Modal） -->\n");
      out.write("		<div class=\"modal fade\" id=\"updateinfo\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-labelledby=\"ModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("							aria-hidden=\"true\">&times;</button>\n");
      out.write("						<h4 class=\"modal-title\" id=\"ModalLabel\">个人资料</h4>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("\n");
      out.write("						<!--正文-->\n");
      out.write("						<input type=\"hidden\" name=\"tip\" value=\"2\"> <input\n");
      out.write("							type=\"hidden\" name=\"url\" value=\"index\">\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">真实姓名</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\"\n");
      out.write("									placeholder=\"请输入您的真实姓名\"\n");
      out.write("									value='${admin.getName()}'> <label\n");
      out.write("									class=\"control-label\" for=\"name\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">手机号</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\"\n");
      out.write("									placeholder=\"请输入您的手机号\"\n");
      out.write("									value='${admin.getPhone()}'> <label\n");
      out.write("									class=\"control-label\" for=\"phone\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\" class=\"col-sm-3 control-label\">邮箱</label>\n");
      out.write("							<div class=\"col-sm-7\">\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\"\n");
      out.write("									placeholder=\"请输入您的邮箱\" value='${admin.getEmail()}'>\n");
      out.write("								<label class=\"control-label\" for=\"email\" style=\"display: none\"></label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\n");
      out.write("						</button>\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">修改</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- /.modal-content -->\n");
      out.write("			</div>\n");
      out.write("			<!-- /.modal -->\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
